var templates = [
    "Create a @noun that will @verb @nouns",
    "Make a @noun that can @adv @verb",
    "Find a way to @adv @verb @nouns",
    "@verb a @noun so that @noun can @adv @verb",
    "Invent a @noun that can @verb @nouns",
    "Tinder for @adj @nouns",
    "Uber for @adj @nouns",
    "Create a new @noun that can @adv @verb",
    "Make a @noun that makes good use of @nouns",
    "Invent a better @adj @noun",
    "Find a way to improve @adj @nouns",
    "Discover a new @adj @noun",
    "3D print a @adj @noun",
    "See if you can @verb a @adj @noun @adv",
    "@verb @noun @adj so that we can @verb @noun @noun @adv",
    "Implement a more efficient @noun",
    "Build a @noun using nothing but @nouns",
    "Find a solution for @adj @nouns",
    "Build a robotic @noun",
    "Hack together a @adj @noun",
    "@nouns can @verb but you can make them @verb as well",
    "Find a @noun that synergizes with @noun",
    "Disrupt the market for @adj @nouns",
    "Solve @noun",
    "Adapt @noun for @nouns",
    "Cure @noun",
    "Alter the design for @nouns so that they work with @adj @nouns",
    "Find a way to make @adj @nouns more diverse and accessible",
    "See if you can make @adj @nouns cheaper",
    "Cure @noun using @noun for mankind",
    "Create a @noun to end all @nouns",
    "Find a way to @adv @verb @nouns",
    "Build a @noun that is more @adj and @adj",
    "Build something so people can finally @verb their @nouns",
    "Reduce the barrier of entry for @adj @noun development",
    "C++ implementation of @adj @nouns",
    "Python script to @verb a @noun",
    "Java code to @adv @verb @nouns",
    "@verb @nouns in a new and exciting way",
    "Military-focused @nouns and @nouns",
    "VR-enabled @adj @nouns",
    "@noun for @nouns",
    "A @adj @noun that can @verb @nouns",
    "See if you can @verb @nouns so that they are @adj and @adj",
    "Try to @verb @nouns so as to @verb @adj @nouns @adv"
];

module.exports = templates;
